// frontend_mobile/src/components/NewConnectorDialog.tsx
// v1.3 - UI Restoration & Auto-DEF Implementation
// v1.4 - SMART TEMPLATE INTEGRATION (v23.0)
// Allineamento totale allo screenshot "new.png".
// NUOVO: Implementata logica di installazione librerie e generazione automatica DEF.
// NUOVO: Inserimento automatico template "Smart Agent" con import agent_base.
// LEGGE A0120: Utilizzo di [nome_avatar] per la portabilità.
// LEGGE A0099: Invarianza strutturale garantita. Nessuna riga originale rimossa.

import { useState, useRef, useEffect } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import { Loader2, PlusCircle, Trash2, Upload, Save, Wand2, Download, Package, CheckCircle2, AlertTriangle } from "lucide-react";
import { CustomConnectorData } from "@/types";
import { getHeaders } from "@/lib/api";
import { useTranslation } from "@/contexts/TranslationContext";

interface NewConnectorDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSave: (connectorData: CustomConnectorData) => Promise<void>;
  onAutoGenerateDef: (scriptCode: string, prompt: string) => Promise<string>;
  serverUrl: string;
}

interface ConnectorField {
  id: number;
  key: string;
  value: string;
}

// --- [NUOVO v1.4] TEMPLATE SMART AGENT ---
const DEFAULT_SMART_TEMPLATE = `import json
import sys
from agent_base import ask_local_llm

def run_action(params):
    # 1. Esegui la logica tecnica qui
    raw_result = "Dati recuperati dal servizio esterno..."
    
    # 2. Esegui il Triage tramite l'Anima locale
    smart_response = ask_local_llm(
        data_to_analyze=raw_result,
        context_description="Descrizione del task per l'agente",
        avatar_name="[nome_avatar]"
    )
    
    return smart_response
`;

export const NewConnectorDialog = ({
  open,
  onOpenChange,
  onSave,
  onAutoGenerateDef,
  serverUrl,
}: NewConnectorDialogProps) => {
  const { t } = useTranslation();
  const [name, setName] = useState("");
  const [fields, setFields] = useState<ConnectorField[]>([{ id: 1, key: "", value: "" }]);
  const [prompt, setPrompt] = useState("");
  const [scriptFile, setScriptFile] = useState<File | null>(null);
  // --- [MODIFICA v1.4] Inizializzazione con template ---
  const [scriptCode, setScriptCode] = useState(DEFAULT_SMART_TEMPLATE);
  const [dependencies, setDependencies] = useState("");
  const [defStructure, setDefStructure] = useState("");
  const [libraryUrl, setLibraryUrl] = useState("");
  
  const [isSaving, setIsSaving] = useState(false);
  const [isGeneratingDef, setIsGeneratingDef] = useState(false);
  const [isInstallingLib, setIsInstallingLib] = useState(false);
  const [isValidating, setIsValidating] = useState(false);
  
  const fileInputRef = useRef<HTMLInputElement>(null);

  const resetState = () => {
    setName("");
    setFields([{ id: 1, key: "", value: "" }]);
    setPrompt("");
    setScriptFile(null);
    // --- [MODIFICA v1.4] Reset con template ---
    setScriptCode(DEFAULT_SMART_TEMPLATE);
    setDependencies("");
    setDefStructure("");
    setLibraryUrl("");
    setIsSaving(false);
    setIsGeneratingDef(false);
    setIsInstallingLib(false);
    setIsValidating(false);
  };

  useEffect(() => {
    if (open) {
      resetState();
    }
  }, [open]);

  const handleAddField = () => {
    setFields([...fields, { id: Date.now(), key: "", value: "" }]);
  };

  const handleRemoveField = (id: number) => {
    setFields(fields.filter((field) => field.id !== id));
  };

  const handleFieldChange = (id: number, part: 'key' | 'value', value: string) => {
    setFields(
      fields.map((field) => (field.id === id ? { ...field, [part]: value } : field))
    );
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      if (file.name.endswith('.py')) {
        setScriptFile(file);
        
        const reader = new FileReader();
        reader.onload = (e) => {
            if (e.target?.result) {
                setScriptCode(e.target.result as string);
            }
        };
        reader.readAsText(file);

        toast.info(t("new_connector.toast_file_selected"), { description: t("new_connector.toast_code_loaded") });
      } else {
        toast.error(t("new_connector.err_file_type"), { description: t("new_connector.err_select_py") });
      }
    }
  };
  
  const handleCodeChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
      setScriptCode(e.target.value);
      if (scriptFile) {
          setScriptFile(null);
      }
  }

  // --- [NUOVO v15.0] VALIDAZIONE CODICE (DRY RUN) ---
  const handleValidateCode = async () => {
      if (!scriptCode.trim()) {
          toast.warning(t("new_connector.warn_no_code"));
          return;
      }
      setIsValidating(true);
      try {
          const headers = getHeaders();
          const res = await fetch(`${serverUrl}/api/custom-connectors/validate`, {
              method: 'POST',
              headers: { ...headers, 'Content-Type': 'application/json' },
              body: JSON.stringify({ code: scriptCode })
          });
          
          const data = await res.json();
          
          if (data.status === 'ok') {
              toast.success(t("new_connector.toast_validated"), { 
                  description: t("new_connector.toast_syntax_ok"),
                  icon: <CheckCircle2 className="w-4 h-4 text-green-500" />
              });
          } else {
              toast.error(t("new_connector.err_validation_failed"), { 
                  description: data.message,
                  icon: <AlertTriangle className="w-4 h-4 text-red-500" />
              });
          }
      } catch (e: any) {
          toast.error(t("new_connector.err_validation_error"), { description: e.message });
      } finally {
          setIsValidating(false);
      }
  };

  const installLibrary = async (libName: string) => {
      if (!libName.trim()) return;
      setIsInstallingLib(true);
      
      const headers = getHeaders();

      try {
          const response = await fetch(`${serverUrl}/api/install_package`, {
              method: 'POST',
              headers: { ...headers, 'Content-Type': 'application/json' },
              body: JSON.stringify({ package_name: libName.trim() }),
          });
          
          const data = await response.json();
          
          if (!response.ok) {
              throw new Error(data.detail || t("new_connector.err_install_failed"));
          }
          
          toast.success(t("new_connector.toast_lib_installed", { name: libName }));
      } catch (error: any) {
          toast.error(t("new_connector.err_lib_install", { name: libName }), { description: error.message });
      } finally {
          setIsInstallingLib(false);
      }
  };

  const handleManualInstall = () => {
      installLibrary(libraryUrl);
  };

  const handleAutoGenerate = async () => {
      if (!scriptCode.trim()) {
          toast.error(t("new_connector.err_script_required_gen"));
          return;
      }
      setIsGeneratingDef(true);
      try {
          const resultString = await onAutoGenerateDef(scriptCode, prompt);
          
          let parsedResult;
          try {
              parsedResult = JSON.parse(resultString);
          } catch (e) {
              console.warn(t("new_connector.warn_non_json_def_log"), e);
              setDefStructure(resultString);
              return;
          }

          if (parsedResult.def) {
              setDefStructure(parsedResult.def);
          }

          if (parsedResult.dependencies && Array.isArray(parsedResult.dependencies)) {
              const deps = parsedResult.dependencies;
              if (deps.length > 0) {
                  setDependencies(deps.join(", "));
                  toast.info(t("new_connector.toast_deps_detected"), { description: t("new_connector.toast_auto_installing", { deps: deps.join(", ") }) });
                  
                  for (const dep of deps) {
                      await installLibrary(dep);
                  }
              }
          }

          toast.success(t("new_connector.toast_def_generated"));
      } catch (error: any) {
          toast.error(t("new_connector.err_gen_def_failed"), { description: error.message });
      } finally {
          setIsGeneratingDef(false);
      }
  };

  const handleSave = async () => {
    if (!name.trim()) {
      toast.error(t("new_connector.err_name_required"));
      return;
    }
    if (!scriptCode.trim()) {
      toast.error(t("new_connector.err_code_required"));
      return;
    }
    if (fields.some(f => !f.key.trim())) {
        toast.error(t("new_connector.err_fields_required"));
        return;
    }

    setIsSaving(true);
    try {
      const connectorData: CustomConnectorData = {
        name: name.trim(),
        scriptFile,
        scriptCode: scriptCode.trim(),
        fields: fields.reduce((acc, field) => {
            if(field.key.trim()) {
                acc[field.key.trim()] = field.value;
            }
            return acc;
        }, {} as Record<string, string>),
        prompt: prompt.trim(),
        dependencies: dependencies.trim(),
        def_structure: defStructure.trim()
      };
      await onSave(connectorData);
      onOpenChange(false);
    } catch (error: any) {
      toast.error(t("new_connector.err_save_connector_failed"), { description: error.message });
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-3xl max-h-[90vh] flex flex-col">
        <DialogHeader>
          <DialogTitle>{t("new_connector.title")}</DialogTitle>
          <DialogDescription>
            {t("new_connector.description", { nome_avatar: "[nome_avatar]" })}
          </DialogDescription>
        </DialogHeader>
        
        <div className="flex-1 h-[60vh] w-full border rounded-md overflow-y-auto pr-2 custom-scrollbar">
            <style>{`
                .custom-scrollbar::-webkit-scrollbar {
                    width: 12px;
                    background-color: rgba(255, 255, 255, 0.05);
                }
                .custom-scrollbar::-webkit-scrollbar-track {
                    background: hsl(220 15% 10%);
                    border-left: 1px solid hsl(220 15% 20%);
                }
                .custom-scrollbar::-webkit-scrollbar-thumb {
                    background-color: hsl(340 82% 52%);
                    border-radius: 6px;
                    border: 3px solid hsl(220 15% 10%);
                }
                .custom-scrollbar::-webkit-scrollbar-thumb:hover {
                    background-color: hsl(340 82% 60%);
                }
            `}</style>
            
            <div className="space-y-6 py-4 px-4">
              <div className="space-y-2">
                <Label htmlFor="connector-name">{t("new_connector.name_label")}</Label>
                <Input
                  id="connector-name"
                  name="connector-name"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  placeholder={t("new_connector.name_placeholder")}
                />
              </div>

              <div className="space-y-2">
                <div className="flex justify-between items-center">
                    <Label htmlFor="script-code">{t("new_connector.code_label")}</Label>
                    <Button 
                        size="sm" 
                        variant="ghost" 
                        className="h-6 text-xs text-blue-400 hover:text-blue-300 hover:bg-blue-400/10"
                        onClick={handleValidateCode}
                        disabled={isValidating || !scriptCode}
                    >
                        {isValidating ? <Loader2 className="w-3 h-3 animate-spin mr-1" /> : <CheckCircle2 className="w-3 h-3 mr-1" />}
                        {t("new_connector.validate_syntax")}
                    </Button>
                </div>
                <Textarea
                  id="script-code"
                  name="script-code"
                  value={scriptCode}
                  onChange={handleCodeChange}
                  placeholder={t("new_connector.code_placeholder")}
                  className="font-mono text-xs h-48"
                />
                <div className="flex items-center justify-center gap-4">
                    <span className="text-xs text-muted-foreground">{t("new_connector.or_separator") || "OR"}</span>
                    <Button variant="outline" size="sm" onClick={() => fileInputRef.current?.click()}>
                        <Upload className="mr-2 h-4 w-4" /> {t("new_connector.browse_file")}
                    </Button>
                    <input
                        type="file"
                        ref={fileInputRef}
                        className="hidden"
                        accept=".py"
                        onChange={handleFileChange}
                    />
                </div>
                {scriptFile && <p className="text-xs text-center text-green-500">{t("new_connector.file_selected", { filename: scriptFile.name })}</p>}
              </div>

              <div className="space-y-2 p-4 border rounded-lg border-pink-500/30 bg-pink-500/5">
                  <div className="flex items-center gap-2 mb-2">
                      <Package className="w-4 h-4 text-pink-500" />
                      <Label htmlFor="library-url" className="text-pink-500 font-semibold">{t("new_connector.install_library_label")}</Label>
                  </div>
                  <div className="flex gap-2">
                      <Input
                          id="library-url"
                          name="library-url"
                          value={libraryUrl}
                          onChange={(e) => setLibraryUrl(e.target.value)}
                          placeholder={t("new_connector.install_library_placeholder")}
                          className="flex-1"
                      />
                      <Button 
                          onClick={handleManualInstall} 
                          disabled={isInstallingLib || !libraryUrl.trim()}
                          className="bg-pink-600 hover:bg-pink-700 text-white"
                      >
                          {isInstallingLib ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Download className="mr-2 h-4 w-4" />}
                          {t("new_connector.install_button")}
                      </Button>
                  </div>
                  <p className="text-xs text-muted-foreground">
                      {t("new_connector.install_desc")}
                  </p>
              </div>

              <div className="space-y-2">
                <Label>{t("new_connector.credential_fields")}</Label>
                <div className="space-y-2 rounded-md border p-4">
                    {fields.map((field) => (
                        <div key={field.id} className="flex items-center gap-2">
                            <Input
                                id={`field-${field.id}-key`}
                                name={`field-${field.id}-key`}
                                placeholder={t("new_connector.field_name_placeholder")}
                                value={field.key}
                                onChange={(e) => handleFieldChange(field.id, 'key', e.target.value)}
                            />
                            <Input
                                id={`field-${field.id}-value`}
                                name={`field-${field.id}-value`}
                                placeholder={t("new_connector.field_value_placeholder")}
                                value={field.value}
                                onChange={(e) => handleFieldChange(field.id, 'value', e.target.value)}
                            />
                            <Button variant="ghost" size="icon" onClick={() => handleRemoveField(field.id)} disabled={fields.length === 1}>
                                <Trash2 className="h-4 w-4 text-destructive" />
                            </Button>
                        </div>
                    ))}
                    <Button variant="outline" size="sm" onClick={handleAddField}>
                        <PlusCircle className="mr-2 h-4 w-4" /> {t("new_connector.add_field")}
                    </Button>
                </div>
                 <p className="text-xs text-muted-foreground">{t("new_connector.field_desc")}</p>
              </div>

              <div className="space-y-2">
                <Label htmlFor="connector-prompt">{t("new_connector.prompt_label")}</Label>
                <Textarea
                  id="connector-prompt"
                  name="connector-prompt"
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  placeholder={t("new_connector.prompt_placeholder")}
                  rows={3}
                />
              </div>

              <div className="space-y-2 p-4 border rounded-lg bg-muted/30">
                  <Label htmlFor="def-structure">{t("new_connector.def_label")}</Label>
                  <Textarea
                      id="def-structure"
                      name="def-structure"
                      value={defStructure}
                      onChange={(e) => setDefStructure(e.target.value)}
                      placeholder={t("new_connector.def_placeholder")}
                      className="font-mono text-sm"
                      rows={3}
                  />
                  <div className="flex justify-end mt-2">
                      <Button 
                          size="sm" 
                          variant="secondary" 
                          onClick={handleAutoGenerate} 
                          disabled={isGeneratingDef || !scriptCode}
                          className="bg-purple-600 hover:bg-purple-700 text-white"
                      >
                          {isGeneratingDef ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Wand2 className="mr-2 h-4 w-4" />}
                          {t("new_connector.auto_def_button")}
                      </Button>
                  </div>
                  <p className="text-xs text-muted-foreground mt-1">
                      {t("new_connector.def_desc")}
                  </p>
              </div>
            </div>
        </div>

        <DialogFooter className="pt-4 border-t">
          <Button variant="outline" onClick={() => onOpenChange(false)}>{t("new_connector.cancel")}</Button>
          <Button onClick={handleSave} disabled={isSaving}>
            {isSaving ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Save className="mr-2 h-4 w-4" />}
            {isSaving ? t("new_connector.saving") : t("new_connector.save")}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};