// frontend_mobile/src/components/SettingsDialog.tsx
// v70.2 - FIX CRASH UI & MISSING IMPORTS
// FIX: Aggiunto import mancante per i componenti Card (Card, CardHeader, ecc.) che causava ReferenceError.
// MANTENUTO: Specialist Gatekeeper, Demiurgo, Musa, Hive Mind, Percezione.
// LEGGE A0099: Invarianza strutturale garantita. Codice integrale fornito.

import { useState, useEffect, useCallback, useRef } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Switch } from "@/components/ui/switch";
import { Slider } from "@/components/ui/slider"; 
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"; // [FIX v70.2] Import Aggiunto
import { Checkbox } from "@/components/ui/checkbox";
import { ServerConfig, CustomConnectorData, TimeSchedule, PerceptionSettings, PanopticonConfig, McpServerConfig } from "@/types";
import { Globe, Server, KeyRound, Loader2, Save, PlusCircle, Edit, Trash2, Clock, Eye, Video, Link2, AlertTriangle, ShieldCheck, Plus, Mic, Volume2, Wand2, Sparkles, Terminal, Code2, Shield, LogOut, Lock, UserPlus, Users, Smartphone, EyeOff, Check, Power, Music4, BookOpen, FileText, FileJson, Wrench, Zap, ServerCog, Plug } from "lucide-react"; 
import { toast } from "sonner";
import { NewConnectorDialog } from "./NewConnectorDialog";
import { SkillEditorDialog, SkillMetadata } from "./SkillEditorDialog"; 
import { Textarea } from "@/components/ui/textarea";
import { useIsPortrait } from "@/hooks/use-mobile";
import { getBaseUrl, getHeaders } from "@/lib/api";
import { cn } from "@/lib/utils";
import { useTranslation } from "@/contexts/TranslationContext";

interface SettingsDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  config: ServerConfig | null;
  onSave: (config: ServerConfig, credentials: any, prompts: any, connectors: any) => Promise<void>;
  onSaveCustomConnector: (connectorData: CustomConnectorData) => Promise<void>;
  onAutoGenerateDef: (scriptCode: string, prompt: string) => Promise<string>;
  onAutoGenerateSkill: (name: string, description: string) => Promise<string>; 
}

// --- MAPPA DELLE CATEGORIE PER I TAB ---
const TABS_MAPPING: Record<string, string[]> = {
    "google": ["google", "gmail"],
    "microsoft": ["microsoft"],
    "social": ["discord", "telegram", "twilio", "twitter", "reddit", "whatsapp"],
    "projects": ["slack", "trello", "jira", "asana", "notion", "github", "gitlab"],
    "utility": ["rss", "webhook", "ai_research", "ngrok", "forms", "image_gen", "video_gen"],
};

// --- MAPPA CHIRURGICA: SERVIZIO <-> PROMPT ---
const SERVICE_TO_PROMPT_MAP: Record<string, string[]> = {
    "google_api": ["google_calendar_prompt", "google_drive_prompt", "google_sheets_prompt", "google_tasks_prompt", "google_photos_prompt", "google_contacts_prompt"],
    "gmail_api": ["gmail_prompt"],
    "microsoft_api": ["microsoft_outlook_prompt", "microsoft_onedrive_prompt", "microsoft_excel_prompt", "microsoft_todo_prompt"],
    "discord_api": ["discord_prompt"],
    "telegram_api": ["telegram_prompt"],
    "twilio_api": ["twilio_prompt"],
    "twitter_api": ["twitter_prompt"],
    "reddit_api": ["reddit_prompt"],
    "whatsapp_api": ["whatsapp_prompt"],
    "slack_api": ["slack_prompt"],
    "trello_api": ["trello_prompt"],
    "jira_api": ["jira_prompt"],
    "asana_api": ["asana_prompt"],
    "notion_api": ["notion_prompt"],
    "github_api": ["github_prompt"],
    "gitlab_api": ["gitlab_prompt"],
    "rss_api": ["rss_prompt"],
    "webhook_api": ["webhook_prompt"],
    "ai_research_api": ["ai_research_prompt"],
    "forms_api": ["forms_prompt"],
    "wordpress_api": ["wordpress_prompt"],
    "image_gen_api": ["image_gen_prompt"],
    "video_gen_api": ["video_gen_prompt"]
};

export const SettingsDialog = ({
  open,
  onOpenChange,
  config,
  onSave,
  onSaveCustomConnector,
  onAutoGenerateDef,
  onAutoGenerateSkill, 
}: SettingsDialogProps) => {
  const { t } = useTranslation();
  const [ip, setIp] = useState(config?.ip || "127.0.0.1");
  const [port, setPort] = useState(config?.port || "8080");
  const [protocol, setProtocol] = useState<"ws" | "wss">(config?.protocol || "ws");
  const [currentAvatar, setCurrentAvatar] = useState(config?.currentAvatar || "gemma");
  
  const [credentialsData, setCredentialsData] = useState<any>(null);
  const [promptsData, setPromptsData] = useState<any>(null);
  const [customConnectors, setCustomConnectors] = useState<any>(null);
  // --- [NUOVO v124.2] STATO TOOLS NATIVI ---
  const [nativeTools, setNativeTools] = useState<any[]>([]);
  const [timeSchedule, setTimeSchedule] = useState<TimeSchedule>({
      morning: "06:00",
      afternoon: "12:00",
      night: "19:00",
      bed_time: "23:00"
  });
  
  const [perceptionSettings, setPerceptionSettings] = useState<PerceptionSettings>({
      silence_threshold: 25,
      hotword_detection: {
          enabled_by_default: false,
          hotword: "ehi gemma",
          listen_timeout: 2,
          phrase_time_limit: 10
      }
  });

  // --- [NUOVO v118.0] STATO MOTORE VOCALE ---
  const[ttsSettings, setTtsSettings] = useState({
      active_engine: "kokoro",
      vibevoice_url: "http://localhost:8880"
  });

  const[imaginationSettings, setImaginationSettings] = useState({
      enabled: false,
      frequency: "medium",
      engine: "auto"
  });

  // --- [NUOVO] STATO SERVER MCP ---
  const[mcpServers, setMcpServers] = useState<McpServerConfig[]>([]);
  
  const [isMicTesting, setIsMicTesting] = useState(false);
  const [currentVolume, setCurrentVolume] = useState(0);
  const [isCalibrating, setIsCalibrating] = useState(false);
  const audioContextRef = useRef<AudioContext | null>(null);
  const analyserRef = useRef<AnalyserNode | null>(null);
  const sourceRef = useRef<MediaStreamAudioSourceNode | null>(null);
  const animationFrameRef = useRef<number | null>(null);
  const streamRef = useRef<MediaStream | null>(null); 

  const [availableAvatars, setAvailableAvatars] = useState<string[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [isNewConnectorOpen, setIsNewConnectorOpen] = useState(false);
  
  const [isResetConfirmOpen, setIsResetConfirmOpen] = useState(false);
  const [isResetting, setIsResetting] = useState(false);
  const [isTotalWipe, setIsTotalWipe] = useState(false);
  
  const [usersList, setUsersList] = useState<any[]>([]);
  const [newUsername, setNewUsername] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [confirmNewPassword, setConfirmNewPassword] = useState(""); 
  const [showPassword, setShowPassword] = useState(false);
  const [policiesList, setPoliciesList] = useState<any[]>([]);
  const [newPolicyValue, setNewPolicyValue] = useState("");
  const [newPolicyType, setNewPolicyType] = useState<"ip" | "range">("ip");
  const [newPolicyDesc, setNewPolicyDesc] = useState("");
  const [isAddingPolicy, setIsAddingPolicy] = useState(false);
  const [isAddingUser, setIsAddingUser] = useState(false);
  const [isChangingPassword, setIsChangingPassword] = useState(false);
  
  const [editingUserId, setEditingUserId] = useState<string | null>(null);
  const [editUsername, setEditUsername] = useState("");
  const [editPassword, setEditPassword] = useState("");

  // --- [NUOVO v121.0] STATI SOFT SKILLS ---
  const [skills, setSkills] = useState<SkillMetadata[]>([]);
  const [isSkillEditorOpen, setIsSkillEditorOpen] = useState(false);
  const [selectedSkill, setSelectedSkill] = useState<SkillMetadata | null>(null);
  // --- [NUOVO v124.3] STATI PER JSON EDITOR UNIVERSALE ---
  const [jsonEditorMode, setJsonEditorMode] = useState<'skill' | 'tool'>('skill');

  const PASSWORD_REGEX = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/;

  const [activeTab, setActiveTab] = useState("server");
  const isPortrait = useIsPortrait();

  useEffect(() => {
    if (config) {
      setIp(config.ip);
      setPort(config.port);
      setProtocol(config.protocol);
      setCurrentAvatar(config.currentAvatar || "gemma");
    }
  }, [config]);

  useEffect(() => {
      if (!open) {
          stopVisualizer();
      }
      return () => {
          stopVisualizer();
      };
  }, [open]);

  const sanitizeIp = (rawIp: string) => {
      if (!rawIp) return "";
      return rawIp.replace(/^https?:\/\//, '').replace(/\/$/, '').trim();
  };

  const fetchData = useCallback(async () => {
    if (open && config) {
      setIsLoading(true);
      
      const serverUrl = getBaseUrl(config);
      const headers = getHeaders();

      try {
        // [FIX v121.1] Promise.allSettled per resilienza ai fallimenti parziali
        const results = await Promise.allSettled([
          fetch(`${serverUrl}/api/credentials`, { headers }),       // 0
          fetch(`${serverUrl}/api/custom-connectors`, { headers }), // 1
          fetch(`${serverUrl}/api/prompts`, { headers }),           // 2
          fetch(`${serverUrl}/api/exportable-items?item_type=avatar`, { headers }), // 3
          fetch(`${serverUrl}/api/settings/time-schedule`, { headers }), // 4
          fetch(`${serverUrl}/api/settings/perception`, { headers }),    // 5
          fetch(`${serverUrl}/api/settings/imagination`, { headers }),   // 6
          fetch(`${serverUrl}/api/settings/tts`, { headers }),           // 7
          fetch(`${serverUrl}/api/skills`, { headers }),                 // 8
          fetch(`${serverUrl}/api/tools`, { headers }),                  // 9 [NUOVO v124.2]
          fetch(`${serverUrl}/api/settings/mcp`, { headers })            // 10 [NUOVO] MCP
        ]);

        // Helper per estrarre dati sicuri
        const getJson = async (result: PromiseSettledResult<Response>, defaultVal: any) => {
            if (result.status === 'fulfilled' && result.value.ok) {
                try { return await result.value.json(); } catch { return defaultVal; }
            }
            if (result.status === 'rejected') console.warn(t("settings_dialog.warn_fetch_failed"), result.reason);
            return defaultVal;
        };

        const credsData = await getJson(results[0], {});
        const connectorsData = await getJson(results[1], {});
        const promptsData = await getJson(results[2], {});
        const avatarsData = await getJson(results[3], Array(0));
        const scheduleData = await getJson(results[4], null);
        const perceptionData = await getJson(results[5], null);
        const imaginationData = await getJson(results[6], null);
        const ttsData = await getJson(results[7], null);
        const skillsData = await getJson(results[8], Array(0));
        const toolsData = await getJson(results[9], Array(0));
        const mcpData = await getJson(results[10], { servers:[] });

        setCredentialsData(credsData);
        setMcpServers(mcpData.servers ||[]);
        setCustomConnectors(connectorsData);
        setPromptsData(promptsData);
        setAvailableAvatars(avatarsData);
        if (scheduleData) setTimeSchedule(scheduleData);
        if (perceptionData) setPerceptionSettings(perceptionData);
        if (imaginationData) setImaginationSettings(imaginationData);
        if (ttsData) setTtsSettings(ttsData);
        setSkills(skillsData);
        setNativeTools(toolsData);

      } catch (error: any) {
        console.error(t("settings_dialog.err_load_config_log"), error);
        toast.error(t("settings_dialog.err_load_config"), { description: error.message });
      } finally {
        setIsLoading(false);
      }
    }
  }, [open, config]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  const fetchUsers = useCallback(async () => {
      try {
          const baseUrl = getBaseUrl(config);
          const res = await fetch(`${baseUrl}/api/auth/users`, { headers: getHeaders() });
          if (res.ok) {
              const data = await res.json();
              setUsersList(data);
          }
      } catch (e) {
          console.error(t("settings_dialog.err_fetch_users"), e);
      }
  }, [config]);

  const fetchPolicies = useCallback(async () => {
      try {
          const baseUrl = getBaseUrl(config);
          const res = await fetch(`${baseUrl}/api/auth/security-policies`, { headers: getHeaders() });
          if (res.ok) {
              const data = await res.json();
              setPoliciesList(data);
          }
      } catch (e) {
          console.error(t("settings_dialog.err_fetch_policies"), e);
      }
  }, [config]);

  const handleAddPolicy = async () => {
      if (!newPolicyValue.trim()) return;
      setIsAddingPolicy(true);
      try {
          const baseUrl = getBaseUrl(config);
          const res = await fetch(`${baseUrl}/api/auth/security-policies`, {
              method: 'POST',
              headers: { ...getHeaders(), 'Content-Type': 'application/json' },
              body: JSON.stringify({
                  type: newPolicyType,
                  value: newPolicyValue.trim(),
                  description: newPolicyDesc.trim() || undefined
              })
          });
          if (res.ok) {
              toast.success(t("settings_dialog.security.toast_policy_added"));
              setNewPolicyValue("");
              setNewPolicyDesc("");
              fetchPolicies();
          } else {
              const err = await res.json();
              throw new Error(err.detail || t("settings_dialog.security.err_add_policy"));
          }
      } catch (e: any) {
          toast.error("Error", { description: e.message });
      } finally {
          setIsAddingPolicy(false);
      }
  };

  const handleDeletePolicy = async (policyId: string) => {
      try {
          const baseUrl = getBaseUrl(config);
          const res = await fetch(`${baseUrl}/api/auth/security-policies/${policyId}`, {
              method: 'DELETE',
              headers: getHeaders()
          });
          if (res.ok) {
              toast.success(t("settings_dialog.security.toast_policy_removed"));
              fetchPolicies();
          }
      } catch (e: any) {
          toast.error("Error", { description: e.message });
      }
  };

  useEffect(() => {
      if (open && activeTab === "security" && config) {
          fetchUsers();
          fetchPolicies();
      }
  }, [open, activeTab, config, fetchUsers, fetchPolicies]);

  const handleDeleteUser = async (userId: string) => {
      try {
          const baseUrl = getBaseUrl(config);
          const res = await fetch(`${baseUrl}/api/auth/users/${userId}`, {
              method: 'DELETE',
              headers: getHeaders()
          });
          if (res.ok) {
              toast.success(t("settings_dialog.security.toast_guardian_removed"));
              fetchUsers();
          } else {
              const err = await res.json();
              throw new Error(err.detail || t("settings_dialog.security.err_delete_failed"));
          }
      } catch (e: any) {
          toast.error("Error", { description: e.message });
      }
  };

  const handleUpdateUser = async (userId: string) => {
      try {
          const baseUrl = getBaseUrl(config);
          const res = await fetch(`${baseUrl}/api/auth/users/${userId}`, {
              method: 'PUT',
              headers: { ...getHeaders(), 'Content-Type': 'application/json' },
              body: JSON.stringify({
                  username: editUsername || undefined,
                  password: editPassword || undefined
              })
          });
          if (res.ok) {
              toast.success(t("settings_dialog.security.toast_guardian_updated"));
              setEditingUserId(null);
              setEditUsername("");
              setEditPassword("");
              fetchUsers();
          } else {
              const err = await res.json();
              throw new Error(err.detail || t("settings_dialog.security.err_update_failed"));
          }
      } catch (e: any) {
          toast.error("Error", { description: e.message });
      }
  };

  const startVisualizer = async () => {
      if (!window.isSecureContext && window.location.hostname !== 'localhost' && window.location.hostname !== '127.0.0.1') {
          toast.error(t("settings_dialog.err_mic_https"));
          return;
      }

      try {
          const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
          streamRef.current = stream;

          const audioContext = new (window.AudioContext || (window as any).webkitAudioContext)();
          const analyser = audioContext.createAnalyser();
          const source = audioContext.createMediaStreamSource(stream);
          source.connect(analyser);
          analyser.fftSize = 256;
          
          audioContextRef.current = audioContext;
          analyserRef.current = analyser;
          sourceRef.current = source;

          const bufferLength = analyser.frequencyBinCount;
          const dataArray = new Uint8Array(bufferLength);

          const updateVolume = () => {
              if (!analyserRef.current) return;
              analyserRef.current.getByteFrequencyData(dataArray);
              let sum = 0;
              for(let i = 0; i < bufferLength; i++) {
                  sum += dataArray[i];
              }
              const average = sum / bufferLength;
              setCurrentVolume(average);
              animationFrameRef.current = requestAnimationFrame(updateVolume);
          };
          updateVolume();
          setIsMicTesting(true);
      } catch (err: any) {
          console.error(t("settings_dialog.err_visualizer"), err);
          if (err.name === 'NotAllowedError' || err.name === 'PermissionDeniedError') {
              toast.error(t("settings_dialog.err_mic_permission"));
          } else {
              toast.error(t("settings_dialog.err_mic_access"), { description: err.message });
          }
      }
  };

  const stopVisualizer = () => {
      if (animationFrameRef.current) {
          cancelAnimationFrame(animationFrameRef.current);
          animationFrameRef.current = null;
      }
      
      if (sourceRef.current) {
          sourceRef.current.disconnect();
          sourceRef.current = null;
      }
      
      if (streamRef.current) {
          streamRef.current.getTracks().forEach(track => track.stop());
          streamRef.current = null;
      }

      if (audioContextRef.current) {
          if (audioContextRef.current.state !== 'closed') {
              audioContextRef.current.close().catch(console.error);
          }
          audioContextRef.current = null;
      }
      
      analyserRef.current = null;
      setCurrentVolume(0);
      setIsMicTesting(false);
      setIsCalibrating(false);
  };

  const toggleMicTest = () => {
      if (isMicTesting) stopVisualizer();
      else startVisualizer();
  };

  const handleAutoCalibrate = async () => {
      if (isCalibrating) return;
      setIsCalibrating(true);
      
      if (!isMicTesting) {
          await startVisualizer();
      }
      
      toast.info(t("settings_dialog.schedule.toast_calibrating"), { description: t("settings_dialog.schedule.toast_silent_desc") });
      
      let samples: number[] = [];
      const sampleInterval = setInterval(() => {
          samples.push(currentVolume); 
      }, 100);

      setTimeout(() => {
          clearInterval(sampleInterval);
          if (samples.length > 0) {
              const avg = samples.reduce((a, b) => a + b, 0) / samples.length;
              const newThreshold = Math.min(255, Math.floor(avg + 10));
              
              setPerceptionSettings(prev => ({ ...prev, silence_threshold: newThreshold }));
              toast.success(t("settings_dialog.schedule.toast_calib_complete"), { description: t("settings_dialog.schedule.toast_threshold_set", { threshold: newThreshold }) });
          }
          setIsCalibrating(false);
      }, 3000);
  };

  const handleSave = async () => {
    if (!ip.trim() || !port.trim()) {
      toast.error(t("settings_dialog.server.ip_port_required"));
      return;
    }
    
    const cleanIp = sanitizeIp(ip);
    const serverUrl = getBaseUrl(config);
    const headers = { ...getHeaders(), "Content-Type": "application/json" };
    
    setIsSaving(true);
    try {
        // Salvataggio schedulazione oraria
        await fetch(`${serverUrl}/api/settings/time-schedule`, {
            method: 'POST',
            headers: headers,
            body: JSON.stringify(timeSchedule)
        });

        // Salvataggio percezione (soglia mic)
        await fetch(`${serverUrl}/api/settings/perception`, {
            method: 'POST',
            headers: headers,
            body: JSON.stringify(perceptionSettings)
        });

        // Salvataggio immaginazione (Musa)
        await fetch(`${serverUrl}/api/settings/imagination`, {
            method: 'POST',
            headers: headers,
            body: JSON.stringify(imaginationSettings)
        });

        // Salvataggio motore vocale (TTS)
        await fetch(`${serverUrl}/api/settings/tts`, {
            method: 'POST',
            headers: headers,
            body: JSON.stringify(ttsSettings)
        });

        // Salvataggio MCP Servers
        await fetch(`${serverUrl}/api/settings/mcp`, {
            method: 'POST',
            headers: headers,
            body: JSON.stringify({ servers: mcpServers })
        });

        const serverConfigToSave = {
          ip: cleanIp,
          port: port.trim(),
          protocol,
          currentAvatar,
        };
        
        await onSave(
            serverConfigToSave, 
            credentialsData || {}, 
            promptsData || {}, 
            customConnectors || {}
        );
        
        toast.success(t("settings_dialog.actions.save_success"));
        onOpenChange(false); 

    } catch (error: any) {
        toast.error(t("settings_dialog.actions.save_error"), { description: error.message });
    } finally {
        setIsSaving(false);
    }
  };

  // --- [NUOVO] HANDLERS MCP SERVER ---
  const handleAddMcpServer = () => {
      const newServer: McpServerConfig = {
          id: crypto.randomUUID(),
          name: "New MCP Server",
          transport: "stdio",
          command: "npx",
          args:["-y", "@modelcontextprotocol/server-sqlite", "--", "db.sqlite"],
          enabled: true
      };
      setMcpServers([...mcpServers, newServer]);
  };

  const handleUpdateMcpServer = (id: string, field: keyof McpServerConfig, value: any) => {
      setMcpServers(mcpServers.map(s => s.id === id ? { ...s, [field]: value } : s));
  };

  const handleDeleteMcpServer = (id: string) => {
      if (confirm(t("settings_dialog.mcp.delete_confirm"))) {
          setMcpServers(mcpServers.filter(s => s.id !== id));
      }
  };

  const handleFactoryReset = async () => {
    setIsResetting(true);
    const serverUrl = getBaseUrl(config);
    const headers = getHeaders();

    try {
        const response = await fetch(`${serverUrl}/api/factory-reset`, {
            method: 'POST',
            headers: { ...headers, 'Content-Type': 'application/json' },
            body: JSON.stringify({ total_wipe: isTotalWipe })
        });

        if (!response.ok) throw new Error(t("settings_dialog.purge.err_backend_reset"));

        localStorage.clear();
        
        toast.success(t("settings_dialog.purge.toast_reset_initiated"), { 
            description: t("settings_dialog.purge.toast_reset_desc") 
        });

        setTimeout(() => {
            setIsResetting(false);
            setIsResetConfirmOpen(false);
            onOpenChange(false);
            window.location.href = "/mobile/";
        }, 3000);

    } catch (error: any) {
        toast.error(t("settings_dialog.purge.err_reset_failed"), { description: error.message });
        setIsResetting(false);
    }
  };
  
  const handleCredentialChange = (service: string, key: string, value: any) => {
      setCredentialsData((prev: any) => ({
          ...prev,
          [service]: {
              ...prev?.[service],
              [key]: value,
          }
      }));
  };

  const getSystemPrompts = () => {
      if (!promptsData?.system) return {};
      return promptsData.system.system || promptsData.system;
  };

  const getConnectorPrompts = () => {
      const system = getSystemPrompts();
      return system.connettori || {};
  };

  const handlePromptChange = (scope: 'system' | 'rpg' | 'connectors', key: string, value: string) => {
    setPromptsData((prev: any) => {
        const newData = { ...prev };
        
        if (scope === 'connectors') {
            if (newData.system && newData.system.system) {
                if (!newData.system.system.connettori) newData.system.system.connettori = {};
                newData.system.system.connettori[key] = value;
            } else {
                if (!newData.system) newData.system = {};
                if (!newData.system.connettori) newData.system.connettori = {};
                newData.system.connettori[key] = value;
            }
        }
        
        return newData;
    });
  };

  const handleSaveConnectorWrapper = async (connectorData: CustomConnectorData) => {
      await onSaveCustomConnector(connectorData);
      await fetchData();
  };

  // --- [AGGIORNATO v124.3] HANDLERS JSON EDITOR (SKILLS & TOOLS) ---
  const handleSaveSkill = async (filename: string, content: string, type: 'skill' | 'tool') => {
      const serverUrl = getBaseUrl(config);
      const headers = { ...getHeaders(), "Content-Type": "application/json" };
      // Endpoint dinamico basato sul tipo
      const endpoint = type === 'skill' ? 'skills' : 'tools';
      
      try {
          const res = await fetch(`${serverUrl}/api/${endpoint}`, {
              method: 'POST',
              headers,
              body: JSON.stringify({ filename, content })
          });
          if (!res.ok) throw new Error(t("settings_dialog.custom.err_save_failed", { type }));
          toast.success(t("settings_dialog.custom.toast_save_success", { type: type.charAt(0).toUpperCase() + type.slice(1) }));
          await fetchData();
      } catch (error: any) {
          toast.error(t("settings_dialog.custom.err_save_error", { type }), { description: error.message });
      }
  };

  const handleDeleteSkill = async (filename: string) => {
      if (!confirm(t("settings_dialog.custom.confirm_delete_skill", { filename }))) return;
      const serverUrl = getBaseUrl(config);
      const headers = getHeaders();
      try {
          const res = await fetch(`${serverUrl}/api/skills/${filename}`, {
              method: 'DELETE',
              headers
          });
          if (!res.ok) throw new Error(t("settings_dialog.custom.err_delete_skill"));
          toast.success(t("settings_dialog.custom.toast_skill_deleted"));
          await fetchData();
      } catch (error: any) {
          toast.error(t("settings_dialog.custom.err_delete_error"), { description: error.message });
      }
  };

  const handleAutoGenerateSkillWrapper = async (name: string, description: string): Promise<string> => {
      // Utilizza la prop passata da Index.tsx per coerenza con il sistema WebSocket
      return onAutoGenerateSkill(name, description);
  };

  const handleLogout = () => {
      localStorage.removeItem("airis_auth_token");
      window.location.reload();
  };

  const handleChangePassword = async () => {
      if (!newPassword || !confirmNewPassword) {
          toast.warning(t("settings_dialog.security.warn_fill_fields"));
          return;
      }
      if (newPassword !== confirmNewPassword) {
          toast.error(t("settings_dialog.security.err_pass_mismatch"));
          return;
      }
      if (newPassword.length < 8) {
          toast.error(t("settings_dialog.security.err_pass_min_chars"));
          return;
      }

      setIsChangingPassword(true);
      setTimeout(() => {
          toast.info(t("settings_dialog.security.toast_coming_soon"), { description: t("settings_dialog.security.toast_coming_soon_desc") });
          setIsChangingPassword(false);
          setNewPassword("");
          setConfirmNewPassword("");
      }, 1000);
  };

  const handleAddUser = async () => {
      if (!newUsername || !newPassword) {
          toast.warning(t("settings_dialog.security.warn_fill_fields"));
          return;
      }
      if (newPassword !== confirmPassword) {
          toast.error(t("settings_dialog.security.err_pass_mismatch"));
          return;
      }
      if (!PASSWORD_REGEX.test(newPassword)) {
          toast.error(t("login_mask.err_pass_weak"), { description: t("settings_dialog.security.err_pass_requirements") });
          return;
      }

      setIsAddingUser(true);
      try {
          const baseUrl = getBaseUrl(config);
          const res = await fetch(`${baseUrl}/api/auth/setup`, {
              method: 'POST',
              headers: { ...getHeaders(), 'Content-Type': 'application/json' },
              body: JSON.stringify({ 
                  username: newUsername, 
                  password: newPassword, 
                  confirm_password: confirmPassword 
              })
          });

          if (res.ok) {
              toast.success(t("settings_dialog.security.toast_user_added"));
              setNewUsername("");
              setNewPassword("");
              setConfirmPassword("");
              fetchUsers();
          } else {
              const err = await res.json();
              throw new Error(err.detail || t("settings_dialog.security.err_add_user_failed"));
          }
      } catch (e: any) {
          toast.error(t("settings_dialog.security.error"), { description: e.message });
      } finally {
          setIsAddingUser(false);
      }
  };

  const renderDynamicTabContent = (tabName: string) => {
      const prefixes = TABS_MAPPING[tabName] || [];
      const allCredentials = credentialsData || {};
      const allPrompts = getConnectorPrompts();
      
      const services = Object.keys(allCredentials).filter(serviceKey => 
          prefixes.some(p => serviceKey.startsWith(p))
      );

      if (services.length === 0) {
          return <p className="text-muted-foreground text-center py-8">{t("settings_dialog.dynamic.no_config", { tab: tabName })}</p>;
      }

      return (
          <div className="space-y-6">
              <Accordion type="multiple" className="w-full">
                  {services.map(serviceKey => {
                      const associatedPrompts = SERVICE_TO_PROMPT_MAP[serviceKey] || [];
                      
                      return (
                          <AccordionItem value={serviceKey} key={serviceKey}>
                              <AccordionTrigger className="font-bold uppercase">{serviceKey.replace(/_/g, ' ')}</AccordionTrigger>
                              <AccordionContent className="space-y-6 pl-2">
                                  
                                  <div className="space-y-4">
                                      {Object.entries(allCredentials[serviceKey]).map(([key, value]) => {
                                          if (key === 'monitoring_enabled' || key === 'stream_template' || key.startsWith('fallback_stream')) return null;
                                          return (
                                              <div key={key} className="space-y-1">
                                                  <Label className="text-xs font-medium text-muted-foreground">{key}</Label>
                                                  <Input value={String(value)} onChange={(e) => handleCredentialChange(serviceKey, key, e.target.value)} />
                                              </div>
                                          );
                                      })}
                                  </div>

                                  {associatedPrompts.length > 0 && (
                                      <div className="space-y-4 pt-4 border-t border-white/10">
                                          <Label className="text-xs font-bold text-primary uppercase tracking-wider">{t("settings_dialog.dynamic.associated_prompts")}</Label>
                                          {associatedPrompts.map(promptKey => (
                                              <div key={promptKey} className="space-y-2">
                                                  <Label className="text-[10px] font-bold text-muted-foreground uppercase">{promptKey.replace(/_/g, ' ')}</Label>
                                                  <Textarea 
                                                      value={String(allPrompts[promptKey] || "")} 
                                                      onChange={(e) => handlePromptChange('connectors', promptKey, e.target.value)}
                                                      className="h-24 font-mono text-xs bg-background/50"
                                                      placeholder={t("settings_dialog.dynamic.enter_prompt", { key: promptKey })}
                                                  />
                                              </div>
                                          ))}
                                      </div>
                                  )}
                              </AccordionContent>
                          </AccordionItem>
                      );
                  })}
              </Accordion>
          </div>
      );
  };

  return (
    <>
      <Dialog open={open} onOpenChange={onOpenChange}>
        <DialogContent className="sm:max-w-[1220px] max-h-[90vh] flex flex-col overflow-hidden">
          <DialogHeader>
            <DialogTitle>{t("settings_dialog.title")}</DialogTitle>
            <DialogDescription>
              {t("settings_dialog.description")}
            </DialogDescription>
          </DialogHeader>

          <style>{`
            .airis-scrollbar {
                overflow-y: auto !important;
                scrollbar-width: auto;
                scrollbar-color: hsl(340 82% 52%) hsl(220 15% 10%);
            }
            .airis-scrollbar::-webkit-scrollbar {
                width: 12px;
                display: block !important;
                -webkit-appearance: none;
            }
            .airis-scrollbar::-webkit-scrollbar-track {
                background: hsl(220 15% 10%);
                border-left: 1px solid hsl(220 15% 20%);
            }
            .airis-scrollbar::-webkit-scrollbar-thumb {
                background-color: hsl(340 82% 52%);
                border-radius: 6px;
                border: 3px solid hsl(220 15% 10%);
            }
            .airis-scrollbar::-webkit-scrollbar-thumb:hover {
                background-color: hsl(340 82% 60%);
            }
          `}</style>

          <Tabs value={activeTab} onValueChange={setActiveTab} className="flex-1 flex flex-col overflow-hidden min-h-0">
            
            {isPortrait ? (
                <div className="px-1 py-2 shrink-0">
                    <Label className="mb-2 block text-xs text-muted-foreground uppercase tracking-wider">{t("settings_dialog.category")}</Label>
                    <Select value={activeTab} onValueChange={setActiveTab}>
                        <SelectTrigger className="w-full">
                            <SelectValue placeholder={t("settings_dialog.select_category")} />
                        </SelectTrigger>
                        <SelectContent>
                            <SelectItem value="server">{t("settings_dialog.tabs.server")}</SelectItem>
                            <SelectItem value="security">{t("settings_dialog.tabs.security")}</SelectItem> 
                            <SelectItem value="schedule">{t("settings_dialog.tabs.schedule")}</SelectItem>
                            <SelectItem value="voice_engine">{t("settings_dialog.tabs.voice_engine")}</SelectItem> 
                            <SelectItem value="imagination">{t("settings_dialog.tabs.imagination")}</SelectItem>
							<SelectItem value="mcp">{t("settings_dialog.tabs.mcp") || "MCP Servers"}</SelectItem>
							{Object.keys(TABS_MAPPING).map(tab => (
                            <SelectItem key={tab} value={tab}>{tab.charAt(0).toUpperCase() + tab.slice(1)}</SelectItem>
                            ))}
                            <SelectItem value="custom">{t("settings_dialog.tabs.custom")}</SelectItem>
                        </SelectContent>
                    </Select>
                </div>
            ) : (
                <div className="w-full bg-muted/30 rounded-lg p-1 shrink-0 flex justify-center overflow-x-auto [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none][scrollbar-width:none]">
                    <TabsList className="flex flex-nowrap justify-center gap-1 bg-transparent h-auto p-0">
                      <TabsTrigger value="server" className="flex-grow-0">{t("settings_dialog.tabs.server")}</TabsTrigger>
                      <TabsTrigger value="security" className="flex-grow-0">{t("settings_dialog.tabs.security")}</TabsTrigger> 
                      <TabsTrigger value="schedule" className="flex-grow-0">{t("settings_dialog.tabs.schedule")}</TabsTrigger>
                      <TabsTrigger value="voice_engine" className="flex-grow-0">{t("settings_dialog.tabs.voice_engine")}</TabsTrigger>
                      <TabsTrigger value="imagination" className="flex-grow-0">{t("settings_dialog.tabs.imagination")}</TabsTrigger>
                      <TabsTrigger value="mcp" className="flex-grow-0">{t("settings_dialog.tabs.mcp") || "MCP Servers"}</TabsTrigger>
                      {Object.keys(TABS_MAPPING).map(tab => (
                          <TabsTrigger key={tab} value={tab} className="flex-grow-0">{tab.charAt(0).toUpperCase() + tab.slice(1)}</TabsTrigger>
                      ))}
                      <TabsTrigger value="custom" className="flex-grow-0">{t("settings_dialog.tabs.custom")}</TabsTrigger>
                    </TabsList>
                </div>
            )}
            
            <TabsContent value="server" className="flex-1 mt-0 p-4 airis-scrollbar min-h-0">
              <div className="space-y-4 py-4 max-w-md mx-auto">
                <div className="space-y-2">
                  <Label htmlFor="ip">{t("settings_dialog.server.ip")}</Label>
                  <div className="flex items-center gap-2">
                    <Server className="w-4 h-4 text-muted-foreground" />
                    <Input id="ip" name="ip" placeholder="e.g., 192.168.1.108" value={ip} onChange={(e) => setIp(e.target.value)} />
                  </div>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="port">{t("settings_dialog.server.port")}</Label>
                  <div className="flex items-center gap-2">
                    <KeyRound className="w-4 h-4 text-muted-foreground" />
                    <Input id="port" name="port" placeholder="8080" value={port} onChange={(e) => setPort(e.target.value)} />
                  </div>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="protocol">{t("settings_dialog.server.protocol")}</Label>
                  <Select value={protocol} onValueChange={(value: "ws" | "wss") => setProtocol(value)}>
                    <SelectTrigger id="protocol"><SelectValue /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="ws">ws:// (Standard)</SelectItem>
                      <SelectItem value="wss">wss:// (Secure)</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="avatar">{t("settings_dialog.server.avatar")}</Label>
                  <Select value={currentAvatar} onValueChange={(value: string) => setCurrentAvatar(value)}>
                    <SelectTrigger id="avatar"><SelectValue /></SelectTrigger>
                    <SelectContent>
                      {availableAvatars.length > 0 ? (
                        availableAvatars.map((avatarName) => (
                          <SelectItem key={avatarName} value={avatarName.toLowerCase()}>
                            {avatarName}
                          </SelectItem>
                        ))
                      ) : (
                        <SelectItem value="gemma">Default</SelectItem>
                      )}
                    </SelectContent>
                  </Select>
                </div>

                <div className="pt-8 border-t border-white/10">
                    <Button 
                        variant="destructive" 
                        className="w-full bg-red-900/20 hover:bg-red-600 text-red-500 hover:text-white border border-red-500/30 transition-all"
                        onClick={() => setIsResetConfirmOpen(true)}
                    >
                        <Trash2 className="mr-2 h-4 w-4" />
                        {t("settings_dialog.server.factory_reset")}
                    </Button>
                    <p className="text-[10px] text-muted-foreground text-center mt-2">
                        {t("settings_dialog.server.warning")}
                    </p>
                </div>
              </div>
            </TabsContent>

            <TabsContent value="security" className="flex-1 mt-0 p-4 airis-scrollbar min-h-0">
                <div className="space-y-8 py-4 max-w-md mx-auto">
                    <div className="space-y-1 border-b border-white/10 pb-2">
                        <h3 className="text-lg font-medium flex items-center gap-2 text-primary">
                            <ShieldCheck className="w-5 h-5" /> {t("settings_dialog.security.title")}
                        </h3>
                    </div>

                    <div className="space-y-4">
                        <h3 className="text-sm font-bold flex items-center gap-2 text-primary">
                            <Users className="w-4 h-4" /> {t("settings_dialog.security.guardians")}
                        </h3>
                        <div className="space-y-2">
                            {usersList.map(u => (
                                <div key={u.id} className="p-3 rounded-lg border bg-muted/10 flex flex-col gap-2">
                                    <div className="flex items-center justify-between">
                                        <div className="flex items-center gap-2">
                                            <Shield className="w-4 h-4 text-primary/60" />
                                            <span className="font-medium">{u.username}</span>
                                            <span className="text-[10px] bg-primary/20 text-primary px-1.5 rounded uppercase">{u.role}</span>
                                        </div>
                                        <div className="flex gap-1">
                                            <Button size="icon" variant="ghost" className="h-7 w-7" onClick={() => {
                                                setEditingUserId(u.id);
                                                setEditUsername(u.username);
                                                setEditPassword("");
                                            }}><Edit className="w-3.5 h-3.5" /></Button>
                                            <Button size="icon" variant="ghost" className="h-7 w-7 text-destructive" onClick={() => handleDeleteUser(u.id)}><Trash2 className="w-3.5 h-3.5" /></Button>
                                        </div>
                                    </div>
                                    
                                    {editingUserId === u.id && (
                                        <div className="mt-2 p-3 border-t border-white/5 space-y-3 animate-in fade-in slide-in-from-top-2">
                                            <div className="space-y-1">
                                                <Label className="text-[10px] uppercase opacity-60">{t("settings_dialog.security.new_username")}</Label>
                                                <Input className="h-8 text-xs" value={editUsername} onChange={(e) => setEditUsername(e.target.value)} />
                                            </div>
                                            <div className="space-y-1">
                                                <Label className="text-[10px] uppercase opacity-60">{t("settings_dialog.security.new_password")}</Label>
                                                <Input type="password" className="h-8 text-xs" placeholder={t("settings_dialog.security.leave_blank")} value={editPassword} onChange={(e) => setEditPassword(e.target.value)} />
                                            </div>
                                            <div className="flex gap-2">
                                                <Button size="sm" className="flex-1 h-7 text-xs" onClick={() => handleUpdateUser(u.id)}><Check className="w-3 h-3 mr-1" /> {t("settings_dialog.security.save")}</Button>
                                                <Button size="sm" variant="outline" className="flex-1 h-7 text-xs" onClick={() => setEditingUserId(null)}><X className="w-3 h-3 mr-1" /> {t("settings_dialog.security.cancel")}</Button>
                                            </div>
                                        </div>
                                    )}
                                </div>
                            ))}
                        </div>
                    </div>

                    <div className="space-y-4 pt-4 border-t border-white/10">
                        <h3 className="text-sm font-bold flex items-center gap-2 text-primary">
                            <UserPlus className="w-4 h-4" /> {t("settings_dialog.security.add_guardian")}
                        </h3>
                        <div className="p-4 rounded-xl border bg-muted/20 space-y-4">
                            <div className="space-y-2">
                                <Label className="text-[10px] uppercase font-bold opacity-60">{t("settings_dialog.security.username")}</Label>
                                <Input placeholder={t("login_mask.admin_name_placeholder")} value={newUsername} onChange={(e) => setNewUsername(e.target.value)} />
                            </div>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <div className="space-y-2 relative">
                                    <Label className="text-[10px] uppercase font-bold opacity-60">{t("settings_dialog.security.password")}</Label>
                                    <Input type={showPassword ? "text" : "password"} placeholder="••••••••" value={newPassword} onChange={(e) => setNewPassword(e.target.value)} className="pr-10" />
                                    <button className="absolute right-3 top-8 text-muted-foreground hover:text-primary" onClick={() => setShowPassword(!showPassword)}>
                                        {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                                    </button>
                                </div>
                                <div className="space-y-2">
                                    <Label className="text-[10px] uppercase font-bold opacity-60">{t("settings_dialog.security.confirm")}</Label>
                                    <Input type="password" placeholder="••••••••" value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} />
                                </div>
                            </div>
                            <Button className="w-full gap-2" variant="secondary" onClick={handleAddUser} disabled={isAddingUser}>
                                {isAddingUser ? <Loader2 className="w-4 h-4 animate-spin" /> : <UserPlus className="w-4 h-4" />}
                                {t("settings_dialog.security.add_user_btn")}
                            </Button>
                        </div>
                    </div>

                    <div className="space-y-4 pt-4 border-t border-white/10">
                        <h3 className="text-sm font-bold flex items-center gap-2 text-primary"><Globe className="w-4 h-4" /> {t("settings_dialog.security.network")}</h3>
                        
                        <div className="space-y-2">
                            {policiesList.map(p => (
                                <div key={p.id} className="p-2 rounded-lg border bg-muted/5 flex items-center justify-between group">
                                    <div className="flex items-center gap-3 overflow-hidden">
                                        {p.type === 'ip' ? <Smartphone className="w-3.5 h-3.5 text-blue-400" /> : <Network className="w-3.5 h-3.5 text-purple-400" />}
                                        <div className="flex flex-col overflow-hidden">
                                            <span className="text-xs font-mono truncate">{p.value}</span>
                                            {p.description && <span className="text-[9px] text-muted-foreground truncate">{p.description}</span>}
                                        </div>
                                    </div>
                                    <Button 
                                        size="icon" 
                                        variant="ghost" 
                                        className="h-7 w-7 text-muted-foreground hover:text-destructive opacity-0 group-hover:opacity-100 transition-opacity"
                                        onClick={() => handleDeletePolicy(p.id)}
                                    ><Trash2 className="w-3.5 h-3.5" /></Button>
                                </div>
                            ))}
                            {policiesList.length === 0 && <p className="text-[10px] text-center text-muted-foreground italic py-2">{t("settings_dialog.security.no_rules")}</p>}
                        </div>

                        <div className="p-3 rounded-xl border border-dashed bg-muted/10 space-y-3">
                            <div className="flex gap-2">
                                <Select value={newPolicyType} onValueChange={(v: any) => setNewPolicyType(v)}>
                                    <SelectTrigger className="w-[100px] h-8 text-xs"><SelectValue /></SelectTrigger>
                                    <SelectContent>
                                        <SelectItem value="ip">{t("settings_dialog.security.single_ip")}</SelectItem>
                                        <SelectItem value="range">{t("settings_dialog.security.ip_range")}</SelectItem>
                                    </SelectContent>
                                </Select>
                                <Input 
                                    placeholder={newPolicyType === 'ip' ? "192.168.1.50" : "192.168.1.0/24"} 
                                    value={newPolicyValue} 
                                    onChange={(e) => setNewPolicyValue(e.target.value)}
                                    className="h-8 text-xs font-mono flex-1"
                                />
                            </div>
                            <div className="flex gap-2">
                                <Input 
                                    placeholder={t("settings_dialog.security.desc_optional")} 
                                    value={newPolicyDesc} 
                                    onChange={(e) => setNewPolicyDesc(e.target.value)}
                                    className="h-8 text-xs flex-1"
                                />
                                <Button size="sm" className="h-8 px-3" onClick={handleAddPolicy} disabled={isAddingPolicy || !newPolicyValue}>
                                    {isAddingPolicy ? <Loader2 className="w-3 h-3 animate-spin" /> : <Plus className="w-3 h-3" />}
                                </Button>
                            </div>
                        </div>
                    </div>

                    <div className="space-y-4 pt-4 border-t border-white/10">
                        <h3 className="text-sm font-bold flex items-center gap-2 text-primary"><Smartphone className="w-4 h-4" /> {t("settings_dialog.security.device")}</h3>
                        <div className="p-4 rounded-xl border bg-muted/10 border-dashed text-center">
                            <p className="text-xs text-muted-foreground">{t("settings_dialog.security.current_device", { id: localStorage.getItem("airis_device_id") || "Unknown" })}</p>
                        </div>
                    </div>

                    <div className="space-y-4 p-4 bg-muted/10 rounded-lg border border-white/5">
                        <div className="flex items-center gap-2 mb-2">
                            <LogOut className="w-4 h-4 text-red-400" />
                            <Label className="font-bold text-red-400">{t("settings_dialog.security.session_control")}</Label>
                        </div>
                        <Button onClick={handleLogout} variant="destructive" className="w-full">{t("settings_dialog.security.logout")}</Button>
                    </div>
                </div>
            </TabsContent>

            <TabsContent value="schedule" className="flex-1 mt-0 p-4 airis-scrollbar min-h-0">
                <div className="space-y-8 py-4 max-w-md mx-auto">
                    
                    <div className="space-y-4">
                        <div className="space-y-1 border-b border-white/10 pb-2">
                            <h3 className="text-lg font-medium flex items-center gap-2"><Clock className="w-5 h-5 text-primary" /> {t("settings_dialog.schedule.title")}</h3>
                            <p className="text-xs text-muted-foreground">{t("settings_dialog.schedule.desc")}</p>
                        </div>
                        <div className="grid gap-4">
                            <div className="grid grid-cols-4 items-center gap-4">
                                <Label htmlFor="morning" className="text-right">{t("settings_dialog.schedule.morning")}</Label>
                                <Input id="morning" type="time" value={timeSchedule.morning} onChange={(e) => setTimeSchedule({...timeSchedule, morning: e.target.value})} className="col-span-3" />
                            </div>
                            <div className="grid grid-cols-4 items-center gap-4">
                                <Label htmlFor="afternoon" className="text-right">{t("settings_dialog.schedule.afternoon")}</Label>
                                <Input id="afternoon" type="time" value={timeSchedule.afternoon} onChange={(e) => setTimeSchedule({...timeSchedule, afternoon: e.target.value})} className="col-span-3" />
                            </div>
                            <div className="grid grid-cols-4 items-center gap-4">
                                <Label htmlFor="night" className="text-right">{t("settings_dialog.schedule.night")}</Label>
                                <Input id="night" type="time" value={timeSchedule.night} onChange={(e) => setTimeSchedule({...timeSchedule, night: e.target.value})} className="col-span-3" />
                            </div>
                            <div className="grid grid-cols-4 items-center gap-4">
                                <Label htmlFor="bed_time" className="text-right">{t("settings_dialog.schedule.bed_time")}</Label>
                                <Input id="bed_time" type="time" value={timeSchedule.bed_time} onChange={(e) => setTimeSchedule({...timeSchedule, bed_time: e.target.value})} className="col-span-3" />
                            </div>
                        </div>
                    </div>

                    <div className="space-y-4">
                        <div className="space-y-1 border-b border-white/10 pb-2">
                            <h3 className="text-lg font-medium flex items-center gap-2"><Mic className="w-5 h-5 text-primary" /> {t("settings_dialog.schedule.hearing")}</h3>
                            <p className="text-xs text-muted-foreground">{t("settings_dialog.schedule.hearing_desc")}</p>
                        </div>
                        
                        <div className="space-y-6 p-4 bg-muted/10 rounded-lg border border-white/5">
                            <div className="space-y-2">
                                <div className="flex justify-between items-center">
                                    <Label className="text-xs uppercase tracking-wider text-muted-foreground">{t("settings_dialog.schedule.mic_level")}</Label>
                                    <span className="text-xs font-mono">{Math.round(currentVolume)} / 255</span>
                                </div>
                                <div className="h-4 bg-black/50 rounded-full overflow-hidden relative border border-white/10">
                                    <div 
                                        className="h-full bg-green-500 transition-all duration-75 ease-out" 
                                        style={{ width: `${(currentVolume / 255) * 100}%` }}
                                    />
                                    <div 
                                        className="absolute top-0 bottom-0 w-0.5 bg-red-500 z-10"
                                        style={{ left: `${(perceptionSettings.silence_threshold / 255) * 100}%` }}
                                    />
                                </div>
                                <div className="flex justify-between text-[10px] text-muted-foreground">
                                    <span>{t("settings_dialog.schedule.silence")}</span>
                                    <span>{t("settings_dialog.schedule.noise")}</span>
                                </div>
                            </div>

                            <div className="space-y-4">
                                <div className="flex justify-between items-center">
                                    <Label>{t("settings_dialog.schedule.threshold")}</Label>
                                    <span className="font-mono text-sm bg-muted px-2 py-1 rounded">{perceptionSettings.silence_threshold}</span>
                                </div>
                                <Slider
                                    value={[perceptionSettings.silence_threshold]}
                                    min={0}
                                    max={255}
                                    step={1}
                                    onValueChange={(val) => setPerceptionSettings(prev => ({ ...prev, silence_threshold: val[0] }))}
                                    className="cursor-pointer"
                                />
                            </div>

                            <div className="flex gap-2">
                                <Button 
                                    variant={isMicTesting ? "destructive" : "secondary"} 
                                    size="sm" 
                                    className="flex-1"
                                    onClick={toggleMicTest}
                                >
                                    {isMicTesting ? <Volume2 className="w-4 h-4 mr-2 animate-pulse" /> : <Mic className="w-4 h-4 mr-2" />}
                                    {isMicTesting ? t("settings_dialog.schedule.stop_test") : t("settings_dialog.schedule.test_mic")}
                                </Button>
                                
                                <Button 
                                    variant="outline" 
                                    size="sm" 
                                    className="flex-1"
                                    onClick={handleAutoCalibrate}
                                    disabled={isCalibrating}
                                >
                                    {isCalibrating ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Wand2 className="w-4 h-4 mr-2" />}
                                    {t("settings_dialog.schedule.auto_calibrate")}
                                </Button>
                            </div>
                        </div>
                    </div>

                </div>
            </TabsContent>

            {/* --- [NUOVO v118.0] TAB VOICE ENGINE --- */}
            <TabsContent value="voice_engine" className="flex-1 mt-0 p-4 airis-scrollbar min-h-0">
                <div className="space-y-8 py-4 max-w-md mx-auto">
                    <div className="space-y-1 border-b border-white/10 pb-2">
                        <h3 className="text-lg font-medium flex items-center gap-2"><Music4 className="w-5 h-5 text-primary" /> {t("settings_dialog.voice_engine.title")}</h3>
                        <p className="text-xs text-muted-foreground">{t("settings_dialog.voice_engine.desc")}</p>
                    </div>

                    <div className="space-y-6 p-4 bg-muted/10 rounded-lg border border-white/5">
                        <div className="space-y-2">
                            <Label>{t("settings_dialog.voice_engine.active")}</Label>
                            <Select 
                                value={ttsSettings.active_engine} 
                                onValueChange={(val) => setTtsSettings(prev => ({ ...prev, active_engine: val }))}
                            >
                                <SelectTrigger>
                                    <SelectValue />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="kokoro">Kokoro-TTS (Native, Stable)</SelectItem>
                                    <SelectItem value="vibevoice">VibeVoice (Expressive, API)</SelectItem>
                                </SelectContent>
                            </Select>
                            <p className="text-[10px] text-muted-foreground mt-1">
                                {ttsSettings.active_engine === 'kokoro' 
                                    ? t("settings_dialog.voice_engine.kokoro_desc") 
                                    : t("settings_dialog.voice_engine.vibevoice_desc")}
                            </p>
                        </div>

                        {ttsSettings.active_engine === 'vibevoice' && (
                            <div className="space-y-2 animate-in fade-in slide-in-from-top-2">
                                <Label>{t("settings_dialog.voice_engine.api_url")}</Label>
                                <div className="flex items-center gap-2">
                                    <Link2 className="w-4 h-4 text-muted-foreground" />
                                    <Input 
                                        value={ttsSettings.vibevoice_url} 
                                        onChange={(e) => setTtsSettings(prev => ({ ...prev, vibevoice_url: e.target.value }))}
                                        placeholder="http://localhost:8880"
                                        className="font-mono text-xs"
                                    />
                                </div>
                                <p className="text-[10px] text-muted-foreground">
                                    {t("settings_dialog.voice_engine.api_desc")}
                                </p>
                            </div>
                        )}
                    </div>
                </div>
            </TabsContent>

            <TabsContent value="imagination" className="flex-1 mt-0 p-4 airis-scrollbar min-h-0">
                <div className="space-y-8 py-4 max-w-md mx-auto">
                    <div className="space-y-1 border-b border-white/10 pb-2">
                        <h3 className="text-lg font-medium flex items-center gap-2"><Sparkles className="w-5 h-5 text-primary" /> {t("settings_dialog.imagination.title")}</h3>
                        <p className="text-xs text-muted-foreground">{t("settings_dialog.imagination.desc")}</p>
                    </div>

                    <div className="space-y-6 p-4 bg-muted/10 rounded-lg border border-white/5">
                        <div className="flex items-center justify-between">
                            <div className="space-y-0.5">
                                <Label className="text-base">{t("settings_dialog.imagination.autonomous")}</Label>
                                <p className="text-xs text-muted-foreground">{t("settings_dialog.imagination.autonomous_desc", { nome_avatar: "[nome_avatar]" })}</p>
                            </div>
                            <Switch
                                checked={imaginationSettings.enabled}
                                onCheckedChange={(checked) => setImaginationSettings(prev => ({ ...prev, enabled: checked }))}
                            />
                        </div>

                        <div className="space-y-2">
                            <Label>{t("settings_dialog.imagination.frequency")}</Label>
                            <Select 
                                value={imaginationSettings.frequency} 
                                onValueChange={(val) => setImaginationSettings(prev => ({ ...prev, frequency: val }))}
                                disabled={!imaginationSettings.enabled}
                            >
                                <SelectTrigger>
                                    <SelectValue />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="low">{t("settings_dialog.imagination.freq_low")}</SelectItem>
                                    <SelectItem value="medium">{t("settings_dialog.imagination.freq_medium")}</SelectItem>
                                    <SelectItem value="high">{t("settings_dialog.imagination.freq_high")}</SelectItem>
                                </SelectContent>
                            </Select>
                            <p className="text-xs text-muted-foreground mt-1">
                                {imaginationSettings.frequency === 'low' && t("settings_dialog.imagination.desc_low", { nome_avatar: "[nome_avatar]" })}
                                {imaginationSettings.frequency === 'medium' && t("settings_dialog.imagination.desc_medium", { nome_avatar: "[nome_avatar]" })}
                                {imaginationSettings.frequency === 'high' && t("settings_dialog.imagination.desc_high", { nome_avatar: "[nome_avatar]" })}
                            </p>
                        </div>

                        <div className="space-y-2">
                            <Label>{t("settings_dialog.imagination.engine")}</Label>
                            <Select 
                                value={imaginationSettings.engine} 
                                onValueChange={(val) => setImaginationSettings(prev => ({ ...prev, engine: val }))}
                            >
                                <SelectTrigger>
                                    <SelectValue />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="auto">{t("settings_dialog.imagination.engine_auto")}</SelectItem>
                                    <SelectItem value="flux">{t("settings_dialog.imagination.engine_flux")}</SelectItem>
                                    <SelectItem value="dalle3">{t("settings_dialog.imagination.engine_dalle3")}</SelectItem>
                                </SelectContent>
                                <p className="text-xs text-muted-foreground mt-1">
                                    {t("settings_dialog.imagination.engine_desc")}
                                </p>
                            </Select>
                        </div>
                    </div>
                </div>
            </TabsContent>

            {/* --- [NUOVO] TAB MCP SERVER --- */}
            <TabsContent value="mcp" className="flex-1 mt-0 p-4 airis-scrollbar min-h-0">
                <div className="space-y-6 py-4 max-w-3xl mx-auto">
                    <div className="flex justify-between items-center border-b border-white/10 pb-2">
                        <div className="space-y-1">
                            <h3 className="text-lg font-medium flex items-center gap-2 text-primary">
                                <ServerCog className="w-5 h-5" /> {t("settings_dialog.mcp.title")}
                            </h3>
                            <p className="text-xs text-muted-foreground">{t("settings_dialog.mcp.desc")}</p>
                        </div>
                        <Button size="sm" onClick={handleAddMcpServer} className="bg-primary hover:bg-primary/90">
                            <Plus className="w-4 h-4 mr-2" /> {t("settings_dialog.mcp.add_server")}
                        </Button>
                    </div>

                    <div className="space-y-4">
                        {mcpServers.length === 0 ? (
                            <div className="text-center py-10 border-2 border-dashed rounded-xl bg-muted/5">
                                <Plug className="w-10 h-10 mx-auto mb-3 text-muted-foreground opacity-50" />
                                <p className="text-sm text-muted-foreground">{t("settings_dialog.mcp.no_servers")}</p>
                            </div>
                        ) : (
                            mcpServers.map((server) => (
                                <Card key={server.id} className="bg-card/50 border-white/5">
                                    <CardHeader className="p-4 pb-2 flex flex-row items-center justify-between">
                                        <div className="flex items-center gap-3">
                                            <Switch 
                                                checked={server.enabled} 
                                                onCheckedChange={(c) => handleUpdateMcpServer(server.id, 'enabled', c)} 
                                            />
                                            <Input 
                                                value={server.name} 
                                                onChange={(e) => handleUpdateMcpServer(server.id, 'name', e.target.value)}
                                                className="h-8 font-bold bg-transparent border-none focus-visible:ring-1 w-[200px]"
                                            />
                                        </div>
                                        <Button variant="ghost" size="icon" className="text-destructive hover:bg-destructive/20" onClick={() => handleDeleteMcpServer(server.id)}>
                                            <Trash2 className="w-4 h-4" />
                                        </Button>
                                    </CardHeader>
                                    <CardContent className="p-4 pt-2 space-y-4">
                                        <div className="space-y-2">
                                            <Label className="text-xs">{t("settings_dialog.mcp.transport")}</Label>
                                            <Select value={server.transport} onValueChange={(v) => handleUpdateMcpServer(server.id, 'transport', v)}>
                                                <SelectTrigger className="h-8 text-xs w-[200px]">
                                                    <SelectValue />
                                                </SelectTrigger>
                                                <SelectContent>
                                                    <SelectItem value="stdio">{t("settings_dialog.mcp.transport_stdio")}</SelectItem>
                                                    <SelectItem value="sse">{t("settings_dialog.mcp.transport_sse")}</SelectItem>
                                                </SelectContent>
                                            </Select>
                                        </div>

                                        {server.transport === 'stdio' ? (
                                            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                                <div className="space-y-2 md:col-span-1">
                                                    <Label className="text-xs">{t("settings_dialog.mcp.command")}</Label>
                                                    <Input 
                                                        value={server.command || ""} 
                                                        onChange={(e) => handleUpdateMcpServer(server.id, 'command', e.target.value)}
                                                        placeholder={t("settings_dialog.mcp.command_placeholder")}
                                                        className="h-8 text-xs font-mono"
                                                    />
                                                </div>
                                                <div className="space-y-2 md:col-span-2">
                                                    <Label className="text-xs">{t("settings_dialog.mcp.args")}</Label>
                                                    {/*[FIX GOD MODE 2.1] Textarea per evitare la rottura dei percorsi con spazi */}
                                                    <Textarea 
                                                        value={server.args ? server.args.join("\n") : ""} 
                                                        onChange={(e) => handleUpdateMcpServer(server.id, 'args', e.target.value.split("\n").filter(a => a.trim() !== ""))}
                                                        placeholder={t("settings_dialog.mcp.args_placeholder") + " (Uno per riga)"}
                                                        className="h-20 text-xs font-mono custom-scrollbar"
                                                    />
                                                </div>
                                            </div>
                                        ) : (
                                            <div className="space-y-2">
                                                <Label className="text-xs">{t("settings_dialog.mcp.url")}</Label>
                                                <Input 
                                                    value={server.url || ""} 
                                                    onChange={(e) => handleUpdateMcpServer(server.id, 'url', e.target.value)}
                                                    placeholder={t("settings_dialog.mcp.url_placeholder")}
                                                    className="h-8 text-xs font-mono"
                                                />
                                            </div>
                                        )}
                                    </CardContent>
                                </Card>
                            ))
                        )}
                    </div>
                </div>
            </TabsContent>

            {/* Tab migrati in Index.tsx */}

            {Object.keys(TABS_MAPPING).map(tab => (
                <TabsContent key={tab} value={tab} className="flex-1 mt-0 p-4 airis-scrollbar min-h-0">
                    {isLoading ? (
                        <div className="flex items-center justify-center h-full py-8"><Loader2 className="w-8 h-8 animate-spin" /></div>
                    ) : renderDynamicTabContent(tab)}
                </TabsContent>
            ))}

            <TabsContent value="custom" className="flex-1 mt-0 p-4 airis-scrollbar min-h-0">
                <div className="space-y-8">
                    
                    {/* --- [NUOVO v124.2] SEZIONE NATIVE TOOLS (src/tools) --- */}
                    <div className="space-y-4">
                        <div className="flex justify-between items-center border-b border-white/10 pb-2">
                            <div className="space-y-0.5">
                                <h3 className="text-lg font-bold flex items-center gap-2 text-blue-400">
                                    <Wrench className="w-5 h-5" /> {t("settings_dialog.custom.native_tools")}
                                </h3>
                                <p className="text-xs text-muted-foreground">{t("settings_dialog.custom.native_desc")}</p>
                            </div>
                        </div>

                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                            {nativeTools.map(tool => (
                                <Card key={tool.filename} className="bg-card/30 border-blue-500/10 hover:border-blue-500/30 transition-all group/tool">
                                    <CardHeader className="p-4 pb-2">
                                        <div className="flex justify-between items-start">
                                            <div className="flex items-center gap-2 overflow-hidden">
                                                <div className="p-2 rounded-lg bg-blue-500/10 text-blue-400">
                                                    <FileJson className="w-4 h-4" />
                                                </div>
                                                <div className="overflow-hidden">
                                                    <CardTitle className="text-sm font-bold truncate">{tool.name.replace(/_/g, ' ')}</CardTitle>
                                                    <CardDescription className="text-[10px] font-mono truncate">{tool.filename}</CardDescription>
                                                </div>
                                            </div>
                                            {/*[NUOVO v124.3] Tasto Edit per Native Tools */}
                                            <div className="opacity-0 group-hover/tool:opacity-100 transition-opacity">
                                                <Button size="icon" variant="ghost" className="h-7 w-7 text-blue-400" onClick={() => {
                                                    setJsonEditorMode('tool');
                                                    setSelectedSkill(tool);
                                                    setIsSkillEditorOpen(true);
                                                }}>
                                                    <Edit className="w-3.5 h-3.5" />
                                                </Button>
                                            </div>
                                        </div>
                                    </CardHeader>
                                    <CardContent className="p-4 pt-0">
                                        <p className="text-[11px] text-muted-foreground line-clamp-2 italic">
                                            {tool.description}
                                        </p>
                                    </CardContent>
                                </Card>
                            ))}
                            {nativeTools.length === 0 && (
                                <div className="col-span-full py-6 text-center border-2 border-dashed rounded-xl bg-muted/5">
                                    <p className="text-xs text-muted-foreground">{t("settings_dialog.custom.no_native")}</p>
                                </div>
                            )}
                        </div>
                    </div>

                    {/* --- SEZIONE SOFT SKILLS (src/skills) --- */}
                    <div className="space-y-4 pt-4 border-t border-white/10">
                        <div className="flex justify-between items-center border-b border-white/10 pb-2">
                            <div className="space-y-0.5">
                                <h3 className="text-lg font-bold flex items-center gap-2 text-primary">
                                    <BookOpen className="w-5 h-5" /> {t("settings_dialog.custom.soft_skills")}
                                </h3>
                                <p className="text-xs text-muted-foreground">{t("settings_dialog.custom.soft_desc")}</p>
                            </div>
                            <Button size="sm" onClick={() => { 
                                setJsonEditorMode('skill');
                                setSelectedSkill(null); 
                                setIsSkillEditorOpen(true); 
                            }} className="bg-primary hover:bg-primary/90">
                                <Plus className="mr-2 h-4 w-4" /> {t("settings_dialog.custom.new_skill")}
                            </Button>
                        </div>

                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                            {skills.map(skill => (
                                <Card key={skill.filename} className="bg-card/50 border-white/5 hover:border-primary/30 transition-all group">
                                    <CardHeader className="p-4 pb-2">
                                        <div className="flex justify-between items-start">
                                            <div className="flex items-center gap-2 overflow-hidden">
                                                <div className="p-2 rounded-lg bg-primary/10 text-primary">
                                                    <FileJson className="w-4 h-4" />
                                                </div>
                                                <div className="overflow-hidden">
                                                    <CardTitle className="text-sm font-bold truncate">{skill.name.replace(/_/g, ' ')}</CardTitle>
                                                    <CardDescription className="text-[10px] font-mono truncate">{skill.filename}</CardDescription>
                                                </div>
                                            </div>
                                            <div className="flex gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                                                <Button size="icon" variant="ghost" className="h-7 w-7" onClick={() => { setSelectedSkill(skill); setIsSkillEditorOpen(true); }}>
                                                    <Edit className="w-3.5 h-3.5" />
                                                </Button>
                                                <Button size="icon" variant="ghost" className="h-7 w-7 text-destructive" onClick={() => handleDeleteSkill(skill.filename)}>
                                                    <Trash2 className="w-3.5 h-3.5" />
                                                </Button>
                                            </div>
                                        </div>
                                    </CardHeader>
                                    <CardContent className="p-4 pt-0">
                                        <p className="text-[11px] text-muted-foreground line-clamp-3 italic">
                                            {skill.description || t("settings_dialog.custom.no_description")}
                                        </p>
                                        {/*[FIX v19.3] Rimossa sottovoce parametri inutile per pulizia UI */}
                                    </CardContent>
                                </Card>
                            ))}
                            {skills.length === 0 && (
                                <div className="col-span-full py-10 text-center border-2 border-dashed rounded-xl bg-muted/5">
                                    <p className="text-sm text-muted-foreground">{t("settings_dialog.custom.no_skills")}</p>
                                </div>
                            )}
                        </div>
                    </div>

                    {/* --- SEZIONE HARD CONNECTORS (.py) --- */}
                    <div className="space-y-4 pt-4 border-t border-white/10">
                        <div className="flex justify-between items-center">
                            <div className="space-y-0.5">
                                <h3 className="text-lg font-bold flex items-center gap-2 text-blue-400">
                                    <Code2 className="w-5 h-5" /> {t("settings_dialog.custom.hard_connectors")}
                                </h3>
                                <p className="text-xs text-muted-foreground">{t("settings_dialog.custom.hard_desc")}</p>
                            </div>
                            <Button size="sm" variant="secondary" onClick={() => setIsNewConnectorOpen(true)}>
                                <PlusCircle className="mr-2 h-4 w-4" /> {t("settings_dialog.custom.new_connector")}
                            </Button>
                        </div>

                        {isLoading ? (
                            <div className="flex items-center justify-center py-8"><Loader2 className="w-8 h-8 animate-spin" /></div>
                        ) : !customConnectors || Object.keys(customConnectors).length === 0 ? (
                            <p className="text-muted-foreground text-center py-8">{t("settings_dialog.custom.no_connectors")}</p>
                        ) : (
                            <Accordion type="multiple" className="w-full">
                                {Object.entries(customConnectors).map(([name, config]: [string, any]) => (
                                    <AccordionItem value={name} key={name} className="border-white/5">
                                        <AccordionTrigger className="font-semibold hover:text-blue-400">{name}</AccordionTrigger>
                                        <AccordionContent className="space-y-4 p-4 border rounded-md bg-muted/10">
                                            <div className="space-y-1">
                                                <Label className="text-[10px] uppercase text-muted-foreground">{t("settings_dialog.custom.script_file")}</Label>
                                                <Input disabled value={config.script_file} className="bg-muted/50 h-8 text-xs font-mono" />
                                            </div>
                                            <div className="space-y-1">
                                                <Label className="text-[10px] uppercase text-muted-foreground">{t("settings_dialog.custom.prompt_def")}</Label>
                                                <div className="p-2 bg-background/50 rounded border border-white/10 text-xs font-mono text-muted-foreground">
                                                    {/* [FIX v108.0] Visualizzazione JSON invece del prompt testuale */}
                                                    {promptsData?.system?.connettori?.[`${name.toLowerCase().replace(/ /g, '_')}_prompt`] 
                                                        ? t("settings_dialog.custom.managed_auto") 
                                                        : t("settings_dialog.custom.no_def")}
                                                </div>
                                            </div>
                                        </AccordionContent>
                                    </AccordionItem>
                                ))}
                            </Accordion>
                        )}
                    </div>
                </div>
            </TabsContent>
          </Tabs>

          <DialogFooter className="pt-4 border-t">
            <Button variant="outline" onClick={() => onOpenChange(false)}>{t("settings_dialog.actions.cancel")}</Button>
            <Button onClick={handleSave} disabled={isSaving || isLoading}>
              {isSaving ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Save className="mr-2 h-4 w-4" />}
              {t("settings_dialog.actions.save_all")}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <AlertDialog open={isResetConfirmOpen} onOpenChange={setIsResetConfirmOpen}>
        <AlertDialogContent className="border-red-500/50 bg-red-950/20 backdrop-blur-xl">
          <AlertDialogHeader>
            <AlertDialogTitle className="flex items-center gap-2 text-red-500">
                <AlertTriangle className="h-6 w-6" />
                {t("settings_dialog.purge.title")}
            </AlertDialogTitle>
            <AlertDialogDescription className="text-red-200/80 text-left">
                {t("settings_dialog.purge.desc1")}<strong>{t("settings_dialog.purge.desc_bold")}</strong>{t("settings_dialog.purge.desc2")}
                <br /><br />
                {t("settings_dialog.purge.point1")}<br/>
                {t("settings_dialog.purge.point2")}<br/>
                {t("settings_dialog.purge.point3")}<br/>
                {t("settings_dialog.purge.point4")}
                <br /><br />
                {t("settings_dialog.purge.question")}<strong>{t("settings_dialog.purge.question_bold")}</strong>{t("settings_dialog.purge.question2")}
                
                <div className="flex items-start space-x-3 mt-6 p-3 bg-red-950/50 border border-red-500/30 rounded-md">
                    <Checkbox 
                        id="total-wipe-settings" 
                        checked={isTotalWipe} 
                        onCheckedChange={(c) => setIsTotalWipe(!!c)} 
                        className="mt-1 border-red-500 data-[state=checked]:bg-red-600 data-[state=checked]:text-white"
                    />
                    <div className="grid gap-1.5 leading-none">
                        <label htmlFor="total-wipe-settings" className="text-sm font-bold leading-none text-red-400 cursor-pointer">
                            {t("index_html.reset_total_wipe")}
                        </label>
                        <p className="text-xs text-red-300/70 leading-snug">
                            {t("index_html.reset_total_wipe_desc")}
                        </p>
                    </div>
                </div>
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel disabled={isResetting}>{t("settings_dialog.purge.btn_cancel")}</AlertDialogCancel>
            <AlertDialogAction 
                onClick={handleFactoryReset}
                disabled={isResetting}
                className="bg-red-600 hover:bg-red-700 text-white"
            >
                {isResetting ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : <Trash2 className="h-4 w-4 mr-2" />}
                {t("settings_dialog.purge.btn_purge")}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      <NewConnectorDialog open={isNewConnectorOpen} onOpenChange={setIsNewConnectorOpen} onSave={handleSaveConnectorWrapper} onAutoGenerateDef={onAutoGenerateDef} serverUrl={getBaseUrl(config)} />
      
      {/* --- [AGGIORNATO v124.3] DIALOGO EDITOR JSON UNIVERSALE --- */}
      <SkillEditorDialog 
        open={isSkillEditorOpen} 
        onOpenChange={setIsSkillEditorOpen} 
        skillToEdit={selectedSkill} 
        serverUrl={getBaseUrl(config)} 
        onSave={handleSaveSkill} 
        onAutoGenerate={handleAutoGenerateSkillWrapper} 
        mode={jsonEditorMode}
      />
    </>
  );
};

// SpecialistSettingsTab migrato in Index.tsx